spring.datasource.url=jdbc:postgresql://localhost:5432/aurum_db
spring.datasource.username=gggooo
spring.datasource.password=admin
# Adding this specifically to avoid the Dialect error from earlier
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080